name: Deploy to Azure Web App (legacy - manual only)

on:
  workflow_dispatch:

env:
  # Replace with your App Service name (e.g., mcp-wikipedia-abc12345)
  AZURE_WEBAPP_NAME: YOUR_APP_SERVICE_NAME
  # Path to deploy (repo root). App Service will build using Oryx when SCM_DO_BUILD_DURING_DEPLOYMENT=true
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run -s lint
        continue-on-error: true

      - name: Build
        run: npm run -s build

      - name: Test
        run: npm test

      - name: Prepare deploy artifact (clean ignored files)
        run: |
          git clean -fdX

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2.2.17
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
name: Legacy workflow disabled

on:
  workflow_dispatch: # keep manual-only, but do nothing

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This legacy workflow has been disabled."
