name: Deploy to Azure App Service (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Set these to match your App Service and resource group
  AZURE_WEBAPP_NAME: tb-wikimcp-wa-gbhzfdgpd9fkasa4
  AZURE_RESOURCE_GROUP: YOUR_RESOURCE_GROUP
  NODE_VERSION: '20.x'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC login
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run -s lint
        continue-on-error: true

      - name: Build
        run: npm run -s build

      - name: Test
        run: npm test

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2.2.17
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '.'
